import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

// NOTE: You would typically need a 'firebase_options.dart' file
// generated by the FlutterFire CLI for proper initialization.
// For demonstration, we assume a basic initialization works.
// In a real project, use:
// await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

void main() async {
  // 1. Initialize Firebase
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Firebase.initializeApp();
  } catch (e) {
    // Handle initialization error
    print('Firebase initialization error: $e');
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Product Inventory Tracker',
      theme: ThemeData(
        primarySwatch: Colors.indigo,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        useMaterial3: true,
      ),
      home: const ProductInventoryScreen(),
    );
  }
}

class ProductInventoryScreen extends StatefulWidget {
  const ProductInventoryScreen({super.key});

  @override
  State<ProductInventoryScreen> createState() => _ProductInventoryScreenState();
}

class _ProductInventoryScreenState extends State<ProductInventoryScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _quantityController = TextEditingController();
  final _priceController = TextEditingController();

  // Firestore instance and collection reference
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static const String _collectionName = 'products';

  @override
  void dispose() {
    _nameController.dispose();
    _quantityController.dispose();
    _priceController.dispose();
    super.dispose();
  }

  /// Saves a new product document to the 'products' Firestore collection.
  Future<void> _addProduct() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();

      try {
        await _firestore.collection(_collectionName).add({
          'name': _nameController.text.trim(),
          'quantity': int.parse(_quantityController.text),
          'price': double.parse(_priceController.text),
          'timestamp': FieldValue.serverTimestamp(), // For ordering
        });

        // Clear the form fields upon successful save
        _nameController.clear();
        _quantityController.clear();
        _priceController.clear();

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Product added successfully!')),
          );
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Failed to add product: $e')),
          );
        }
      }
    }
  }

  /// Calculates the total value of all stock items in the list.
  String _calculateTotalStockValue(List<QueryDocumentSnapshot> documents) {
    double totalValue = 0.0;
    for (var doc in documents) {
      try {
        // Use a safe cast to Map<String, dynamic>
        final data = doc.data() as Map<String, dynamic>;
        
        // Firestore stores numbers as 'num', safely retrieve and convert
        final num quantity = data['quantity'] as num? ?? 0;
        final num price = data['price'] as num? ?? 0.0;
        
        // Calculate and accumulate the value
        totalValue += (quantity.toDouble() * price.toDouble());
      } catch (e) {
        print('Error calculating stock value for a document: $e');
      }
    }
    return totalValue.toStringAsFixed(2);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Product Inventory Tracker'),
        backgroundColor: Colors.indigo,
        foregroundColor: Colors.white,
      ),
      body: Column(
        children: <Widget>[
          // Product Input Form
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Form(
              key: _formKey,
              child: Column(
                children: <Widget>[
                  TextFormField(
                    controller: _nameController,
                    decoration: const InputDecoration(labelText: 'Product Name'),
                    validator: (value) => value == null || value.isEmpty ? 'Enter a name' : null,
                  ),
                  Row(
                    children: [
                      Expanded(
                        child: TextFormField(
                          controller: _quantityController,
                          decoration: const InputDecoration(labelText: 'Quantity'),
                          keyboardType: TextInputType.number,
                          validator: (value) {
                            if (value == null || int.tryParse(value) == null) {
                              return 'Must be an integer';
                            }
                            return null;
                          },
                        ),
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: TextFormField(
                          controller: _priceController,
                          decoration: const InputDecoration(labelText: 'Price (\$)'),
                          keyboardType: TextInputType.number,
                          validator: (value) {
                            if (value == null || double.tryParse(value) == null) {
                              return 'Must be a number';
                            }
                            return null;
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 20),
                  ElevatedButton.icon(
                    onPressed: _addProduct,
                    icon: const Icon(Icons.add_shopping_cart),
                    label: const Text('Save Product'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.indigo,
                      foregroundColor: Colors.white,
                      minimumSize: const Size(double.infinity, 40),
                    ),
                  ),
                ],
              ),
            ),
          ),
          const Divider(),
          
          // Product List and Total Stock Value
          Expanded(
            // StreamBuilder listens for real-time updates from Firestore
            child: StreamBuilder<QuerySnapshot>(
              // Order by timestamp to show most recent first
              stream: _firestore.collection(_collectionName).orderBy('timestamp', descending: true).snapshots(),
              builder: (context, snapshot) {
                if (snapshot.hasError) {
                  return Center(child: Text('Error loading data: ${snapshot.error}'));
                }

                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: CircularProgressIndicator());
                }

                final documents = snapshot.data!.docs;
                if (documents.isEmpty) {
                  return const Center(child: Text('No products in inventory. Add one above!'));
                }
                
                // ListView to display products
                return ListView.builder(
                  itemCount: documents.length,
                  itemBuilder: (context, index) {
                    final product = documents[index].data() as Map<String, dynamic>;
                    final name = product['name'] ?? 'N/A';
                    // Use 'num' for quantity for safe retrieval
                    final int quantity = (product['quantity'] as num?)?.toInt() ?? 0;
                    final double price = (product['price'] as num?)?.toDouble() ?? 0.0;
                    final bool isLowStock = quantity < 5; // Low Stock check

                    return Card(
                      elevation: 1,
                      margin: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                      child: ListTile(
                        title: Text(name, style: const TextStyle(fontWeight: FontWeight.bold)),
                        subtitle: Text('Qty: $quantity | Price: \$${price.toStringAsFixed(2)}'),
                        trailing: isLowStock
                            ? const Text(
                                'Low Stock!',
                                style: TextStyle(color: Colors.red, fontWeight: FontWeight.bold),
                              ) // Highlight products with low stock
                            : null,
                      ),
                    );
                  },
                );
              },
            ),
          ),
          
          // Total Stock Value Display (kept as a separate StreamBuilder for simplicity)
          StreamBuilder<QuerySnapshot>(
            stream: _firestore.collection(_collectionName).snapshots(),
            builder: (context, snapshot) {
              String totalValue = '0.00';
              if (snapshot.hasData) {
                totalValue = _calculateTotalStockValue(snapshot.data!.docs);
              }
              return Container(
                padding: const EdgeInsets.all(16.0),
                width: double.infinity,
                decoration: const BoxDecoration(
                  color: Colors.indigo,
                  boxShadow: [BoxShadow(color: Colors.black26, blurRadius: 5, offset: Offset(0, -2))],
                ),
                child: Text(
                  'Total Stock Value: \$$totalValue',
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              );
            },
          ),
        ],
      ),
    );
  }
}